version: "3.8"
services:
  video-stream-api:
    build: .
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      BLOB_STORAGE_URL: http://blob-storage
      VIDEO_CONVERTER_WEBHOOK_URL: http://video-stream-api:3000/api/v1/video_converter_webhook
      VIDEO_CONVERTER_WEBHOOK_USER_UUID: "968565e6-61f6-45c6-ab68-963eb2c04428"
      VIDEO_CONVERTER_BASE_URL: http://video-converter
      RAILS_DEVELOPMENT_HOSTS: video-stream-api:3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  video-converter:
    image: gustavolim00/video-converter:0.2-test
    environment:
      BLOB_STORAGE_URL: http://blob-storage
      RABBITMQ_HOSTNAME: rabbitmq
      DIRECTORY_WITH_FFMPEG_AND_FFPROBE: "/usr/bin"
      POSTGRES_CONNECTION_STRING: "Host=postgres;Database=file_converter;Username=postgres;Password=postgres"
    depends_on:
      - rabbitmq
      - postgres
    restart: always
    ports:
      - "5001:80"
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: file_converter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  blob-storage:
    image: gustavolim00/blob-storage:1.3
    ports:
      - "5000:80"
    environment:
      - BASE_FOLDER_PATH=/dados
      - APP_PORT=80
      - USE_CORS=true
    volumes:
      - /media/gustavo/0cead188-0fac-43d9-9d67-98cfeb4925ce1/blob-storage:/dados